COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= fifo_full_int.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bmi323.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk